version: '3.8'
services:
  db:
    image: mongo
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatadmin
      MONGO_INITDB_ROOT_PASSWORD: testtest
      MONGO_INITDB_DATABASE: chatdb
    volumes:
      - ./.db-data:/data/db
  sockets:
    image: quay.io/soketi/soketi:latest-16-alpine
    ports:
      - 6001:6001
    #   - 9601:9601
    # environment:
    #   SOKETI_DEBUG: "1"
